import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#000000' },
  shell: { flex: 1, flexDirection: 'row', backgroundColor: '#000000' },
  sidebar: { width: 208, flexBasis: 208, flexGrow: 0, flexShrink: 0, minHeight: 0, overflow: 'hidden', backgroundColor: '#080808', borderRightWidth: 1, borderRightColor: '#292929', paddingHorizontal: 14, paddingTop: 12 },
  sidebarCollapsed: { width: 58, flexBasis: 58, paddingHorizontal: 8 },
  sidebarScroll: { flex: 1, minHeight: 0 },
  sidebarScrollContent: { paddingBottom: 12 },
  brand: { height: 42, flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  brandCollapsed: { justifyContent: 'center' },
  brandCompact: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  brandLogo: { width: 174, height: 40 },
  brandLogoCollapsed: { width: 38, height: 38 },
  brandLogoCompact: { width: 174, height: 44 },
  brandMark: { width: 36, height: 36, borderRadius: 11, backgroundColor: '#f5f5f7', alignItems: 'center', justifyContent: 'center' },
  brandLeaf: { color: '#1d1d1f', fontSize: 21 },
  brandName: { color: '#f5f5f7', fontSize: 23, fontWeight: '600', letterSpacing: -0.6 },
  packhouse: { minHeight: 64, borderRadius: 14, backgroundColor: '#1d1d1f', padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  packhouseIcon: { width: 34, height: 34, borderRadius: 9, backgroundColor: '#333336', alignItems: 'center', justifyContent: 'center' },
  packhouseCopy: { flex: 1, gap: 5 },
  packhouseName: { color: '#f5f5f7', fontSize: 12, fontWeight: '600' },
  packhousePlace: { color: '#86868b', fontSize: 11, lineHeight: 16 },
  chevron: { color: '#86868b' },
  navSection: { color: '#86868b', fontSize: 10, letterSpacing: 0.6, marginHorizontal: 10, marginBottom: 7 },
  navList: { gap: 2 },
  navItem: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, borderRadius: 999, marginBottom: 1 },
  navItemCollapsed: { justifyContent: 'center', paddingHorizontal: 0 },
  navItemActive: { backgroundColor: '#333336' },
  navIcon: { color: '#86868b', width: 18, textAlign: 'center', fontSize: 16 },
  navGlyphBox: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center' },
  navIconActive: { color: '#f5f5f7' },
  navLabel: { color: '#cccccc', fontSize: 13, flex: 1 },
  navLabelActive: { color: '#ffffff', fontWeight: '600' },
  navCount: { color: '#cccccc', backgroundColor: '#1d1d1f', borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3, fontSize: 10 },
  adminSection: { marginTop: 14 },
  collapseButton: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, borderRadius: 999, marginTop: 6, marginBottom: 8 },
  collapseGlyph: { width: 20, color: '#86868b', fontSize: 23, textAlign: 'center' },
  collapseLabel: { color: '#86868b', fontSize: 12 },
  mainArea: { flex: 1, minWidth: 0 },
  topNav: { minHeight: 64, borderBottomWidth: 1, borderBottomColor: '#292929', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 36 },
  topNavCompact: { paddingHorizontal: 12, gap: 6 },
  mobileMenuButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  mobileBrandMark: { width: 32, height: 32 },
  mobileSectionTitle: { flex: 1, minWidth: 0, color: '#f5f5f7', fontSize: 13, fontWeight: '600' },
  mobileMenuOverlay: { flex: 1, flexDirection: 'row' },
  mobileMenuBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(0,0,0,0.72)' },
  mobileMenuPanel: { width: 300, maxWidth: '85%', height: '100%', backgroundColor: '#101010', borderRightWidth: 1, borderRightColor: '#333336' },
  mobileMenuHeader: { minHeight: 64, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  mobileMenuContent: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 28 },
  mobileNavItem: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, borderRadius: 12, marginBottom: 4 },
  breadcrumb: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  menuToggle: { width: 30, height: 30, borderRadius: 9, borderWidth: 1, borderColor: '#333336', alignItems: 'center', justifyContent: 'center' },
  menuToggleText: { color: '#cccccc', fontSize: 15 },
  breadcrumbMuted: { color: '#86868b', fontSize: 11 },
  breadcrumbSlash: { color: '#424245', fontSize: 12 },
  breadcrumbActive: { color: '#f5f5f7', fontSize: 11, fontWeight: '600' },
  topActions: { flexDirection: 'row', alignItems: 'center', gap: 18 },
  topActionsCompact: { gap: 4 },
  search: { width: 255, color: '#86868b', fontSize: 12 },
  topDivider: { width: 1, height: 26, backgroundColor: '#333336' },
  bellButton: { position: 'relative', width: 38, height: 38, borderRadius: 12, borderWidth: 1, borderColor: '#292929', backgroundColor: '#111111', alignItems: 'center', justifyContent: 'center' },
  notificationBellIcon: { alignItems: 'center', justifyContent: 'center' },
  notificationBadge: { position: 'absolute', top: -3, right: -3, minWidth: 16, height: 16, paddingHorizontal: 3, borderRadius: 8, borderWidth: 2, borderColor: '#000000', backgroundColor: '#e45858', alignItems: 'center', justifyContent: 'center' },
  notificationBadgeText: { color: '#ffffff', fontSize: 8, lineHeight: 10, fontWeight: '700' },
  avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#333336', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#f5f5f7', fontSize: 11, fontWeight: '600' },
  content: { paddingHorizontal: 38, paddingTop: 44, paddingBottom: 36, width: '100%', maxWidth: 1500, alignSelf: 'center' },
  producerContent: { paddingHorizontal: 38, paddingTop: 38, paddingBottom: 36, width: '100%', maxWidth: 1500, alignSelf: 'center' },
  reportGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 20 },
  reportGridCompact: { flexDirection: 'column', gap: 14 },
  reportCard: { width: '49%', minHeight: 294, borderRadius: 28, backgroundColor: '#1d1d1f', padding: 28, marginBottom: 0 },
  reportCardCompact: { width: '100%', minHeight: 270, padding: 22, borderRadius: 24 },
  reportIcon: { width: 38, height: 38, borderRadius: 20, backgroundColor: '#333336', alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  reportTitle: { color: '#f5f5f7', fontSize: 21, lineHeight: 27, fontWeight: '600', letterSpacing: -0.25 },
  reportDescription: { color: '#86868b', fontSize: 13, lineHeight: 19, marginTop: 8, marginBottom: 20 },
  reportDates: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  reportDatesCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 4 },
  reportDateInputCompact: { flex: 0, width: '100%' },
  reportDateInput: { flex: 1, minWidth: 0, height: 44, borderRadius: 9999, borderWidth: 1, borderColor: '#333336', paddingHorizontal: 14, color: '#f5f5f7', fontSize: 13, outlineStyle: 'none' } as any,
  reportDash: { color: '#86868b', fontSize: 13 },
  reportDownload: { minHeight: 42, alignSelf: 'flex-start', justifyContent: 'center', borderRadius: 9999, backgroundColor: '#333336', paddingHorizontal: 18, paddingVertical: 10 },
  reportDownloadText: { color: '#ffffff', fontSize: 13 },
  reportError: { color: '#f2a7a7', fontSize: 13, marginBottom: 14 },
  reportFootnote: { color: '#86868b', fontSize: 11, marginTop: 22 },
  contentCompact: { paddingHorizontal: 16, paddingTop: 24 },
  producerHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 20, marginBottom: 36 },
  producerHeadingCompact: { flexDirection: 'column', alignItems: 'stretch', marginBottom: 26 },
  producerTitle: { color: '#f5f5f7', fontSize: 48, lineHeight: 56, fontWeight: '600', letterSpacing: -1.7 },
  producerTitleCompact: { fontSize: 38, lineHeight: 44 },
  exportButton: { minHeight: 42, paddingHorizontal: 17, borderRadius: 9999, backgroundColor: '#333336', justifyContent: 'center' },
  exportText: { color: '#f5f5f7', fontSize: 12 },
  producerStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, marginBottom: 32 },
  paymentStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, marginBottom: 32 },
  paymentMetric: { flex: 1, minWidth: 205, minHeight: 178, borderRadius: 28, backgroundColor: '#1d1d1f', padding: 24, justifyContent: 'space-between' },
  paymentMetricCompact: { flexBasis: '45%', minWidth: 120, minHeight: 148, borderRadius: 22, padding: 16 },
  paymentTable: { minWidth: 1090 },
  paymentNameCol: { width: 265 },
  paymentFolioCol: { width: 105 },
  paymentOrchardCol: { width: 195 },
  paymentAmountCol: { width: 145 },
  paymentStatusCol: { width: 130 },
  paymentActionsCol: { width: 250, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  paymentPending: { color: '#f5b942', backgroundColor: '#382b16' },
  paymentPaid: { color: '#37d67a', backgroundColor: '#183126' },
  paymentMobileFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 4, flexWrap: 'wrap' },
  paymentAmount: { color: '#f5f5f7', fontSize: 14, fontWeight: '600', marginRight: 'auto' },
  registerPaymentButton: { minHeight: 36, paddingHorizontal: 13, borderRadius: 9999, backgroundColor: '#333336', alignItems: 'center', justifyContent: 'center' },
  registerPaymentText: { color: '#f5f5f7', fontSize: 10, fontWeight: '500' },
  paymentProducerOptions: { maxHeight: 130, flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  paymentProducerOption: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 9999, borderWidth: 1, borderColor: '#424245' },
  paymentProducerOptionSelected: { backgroundColor: '#333336', borderColor: '#86868b' },
  paymentProducerOptionText: { color: '#cccccc', fontSize: 11 },
  paymentProducerOptionTextSelected: { color: '#ffffff' },
  paymentStatusOptions: { flexDirection: 'row', gap: 9 },
  paymentStatusOption: { flex: 1, minHeight: 40, justifyContent: 'center', alignItems: 'center', borderRadius: 9999, borderWidth: 1, borderColor: '#424245' },
  paymentStatusOptionSelected: { backgroundColor: '#333336', borderColor: '#86868b' },
  paymentStatusOptionText: { color: '#cccccc', fontSize: 12 },
  paymentStatusOptionTextSelected: { color: '#ffffff' },
  producerStatCard: { width: 240, minHeight: 178, borderRadius: 28, backgroundColor: '#1d1d1f', padding: 24, justifyContent: 'space-between' },
  producerStatCardCompact: { flex: 1, minWidth: 120, minHeight: 145, padding: 16, borderRadius: 22 },
  producerStatNote: { color: '#86868b', fontSize: 11, marginTop: 4 },
  producerToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, marginBottom: 22 },
  producerToolbarCompact: { flexDirection: 'column', alignItems: 'stretch', marginBottom: 16 },
  userFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  userTable: { minWidth: 980 },
  userNameCol: { width: 245 },
  userEmailCol: { width: 280 },
  userRoleCol: { width: 180 },
  userStatusCol: { width: 125 },
  userActionsCol: { width: 235, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', gap: 8 },
  userRoleLine: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  userRoleLabel: { color: '#cccccc', fontSize: 11 },
  userActionButton: { minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 11, borderWidth: 1, borderColor: '#424245', borderRadius: 9999, backgroundColor: '#1d1d1f' },
  userActionText: { color: '#f5f5f7', fontSize: 10, fontWeight: '500' },
  userRolePicker: { flexDirection: 'row', gap: 9 },
  userNoProducers: { color: '#f2a7a7', fontSize: 12, paddingVertical: 8 },
  userNotice: { color: '#f2a7a7', fontSize: 12, lineHeight: 18 },
  producerSearch: { height: 46, width: 320, maxWidth: '100%', borderRadius: 9999, backgroundColor: '#1d1d1f', borderWidth: 1, borderColor: '#333336', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 10 },
  producerSearchCompact: { width: '100%' },
  searchGlyph: { color: '#86868b', fontSize: 20 },
  producerSearchInput: { flex: 1, color: '#f5f5f7', fontSize: 13, outlineStyle: 'none' } as any,
  orchardDetails: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12, paddingLeft: 42 },
  orchardProducerCol: { width: 230 },
  orchardHectaresCol: { width: 120 },
  orchardTenureCol: { width: 110 },
  orchardRowSelected: { backgroundColor: 'rgba(51,51,54,0.45)' },
  mapSection: { marginTop: 36, marginBottom: 24 },
  mapHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  mapHeadingCompact: { flexDirection: 'column', alignItems: 'flex-start', gap: 12 },
  mapLegend: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: '#333336', borderRadius: 9999, paddingHorizontal: 12, paddingVertical: 8 },
  mapLegendText: { color: '#cccccc', fontSize: 11 },
  mapCanvas: { width: '100%', height: 340, overflow: 'hidden', borderRadius: 20, borderWidth: 1, borderColor: '#333336', backgroundColor: '#101713' },
  selectedOrchard: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, borderTopWidth: 1, borderColor: '#333336', paddingHorizontal: 14, marginTop: 10 },
  mapPinMini: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#1d1d1f', alignItems: 'center', justifyContent: 'center' },
  mapPinMiniText: { color: '#2997ff', fontSize: 20 },
  selectedOrchardCopy: { flex: 1, gap: 4 },
  orchardModalScroll: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', padding: 20, width: '100%' },
  modalDescription: { color: '#86868b', fontSize: 12, lineHeight: 18, marginBottom: 6 },
  producerPicker: { gap: 7 },
  producerChoice: { minHeight: 38, justifyContent: 'center', borderWidth: 1, borderColor: '#424245', borderRadius: 10, paddingHorizontal: 12 },
  producerChoiceSelected: { borderColor: '#0071e3', backgroundColor: '#101d2b' },
  producerChoiceText: { color: '#cccccc', fontSize: 12 },
  producerChoiceTextSelected: { color: '#f5f5f7' },
  tenurePicker: { flexDirection: 'row', gap: 8 },
  tenureOption: { flex: 1, minHeight: 40, borderWidth: 1, borderColor: '#424245', borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  tenureOptionSelected: { borderColor: '#0071e3', backgroundColor: '#101d2b' },
  tenureOptionText: { color: '#86868b', fontSize: 12 },
  tenureOptionTextSelected: { color: '#f5f5f7' },
  coordinateRow: { flexDirection: 'row', gap: 10 },
  coordinateInput: { flex: 1, minWidth: 0 },
  modalHint: { color: '#86868b', fontSize: 11 },
  filterButton: { minWidth: 150, minHeight: 44, paddingHorizontal: 17, borderRadius: 9999, borderWidth: 1, borderColor: '#333336', justifyContent: 'center' },
  filterText: { color: '#f5f5f7', fontSize: 13 },
  producerTable: { minWidth: 1115 },
  shipmentTable: { minWidth: 1040 },
  shipmentDestinationCol: { width: 280 },
  shipmentFolioCol: { width: 150 },
  shipmentDateCol: { width: 135 },
  shipmentKilosCol: { width: 155 },
  shipmentStatusCol: { width: 170 },
  shipmentMobileFooter: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  shipmentStatusText: { color: '#f5f5f7', fontSize: 11 },
  shipmentPreparing: { backgroundColor: '#3b3020' },
  shipmentReady: { backgroundColor: '#183323' },
  shipmentTransit: { backgroundColor: '#172d43' },
  shipmentDelivered: { backgroundColor: '#26312a' },
  producerTableHeader: { borderTopWidth: 1, borderTopColor: '#333336', minHeight: 48 },
  producerTableRow: { minHeight: 82, flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#333336' },
  producerColumn: { justifyContent: 'center', paddingHorizontal: 12 },
  producerColumnName: { width: 265 },
  producerColumnFolio: { width: 100 },
  producerColumnLocation: { width: 220 },
  producerColumnRfc: { width: 145 },
  producerColumnKilos: { width: 150 },
  producerColumnStatus: { width: 120 },
  producerColumnActions: { width: 115, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  tableHeading: { color: '#cccccc', fontSize: 10, letterSpacing: 0.2 },
  producerNameCell: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  producerAvatar: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#333336', alignItems: 'center', justifyContent: 'center' },
  producerInitials: { color: '#f5f5f7', fontSize: 10, fontWeight: '600' },
  producerName: { color: '#f5f5f7', fontSize: 12, fontWeight: '600' },
  producerMeta: { color: '#cccccc', fontSize: 12 },
  producerSubMeta: { color: '#86868b', fontSize: 10, marginTop: 4 },
  statusBadge: { alignSelf: 'flex-start', overflow: 'hidden', borderRadius: 9999, paddingHorizontal: 12, paddingVertical: 7, fontSize: 11 },
  statusActive: { color: '#37d67a', backgroundColor: '#1d1d1f' },
  statusInactive: { color: '#cccccc', backgroundColor: '#333336' },
  rowAction: { color: '#f5f5f7', fontSize: 18, paddingHorizontal: 8, paddingVertical: 6 },
  rowDelete: { color: '#cccccc', fontSize: 16, paddingHorizontal: 8, paddingVertical: 6 },
  actionGlyph: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  producerCards: { gap: 10 },
  producerCard: { borderTopWidth: 1, borderColor: '#333336', paddingVertical: 14, gap: 13 },
  producerMobileHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  producerMobileCopy: { flex: 1, minWidth: 0, gap: 5 },
  producerMobileFooter: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  producerKilos: { color: '#cccccc', fontSize: 11, marginRight: 'auto' },
  emptyText: { color: '#86868b', textAlign: 'center', padding: 28 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.75)', alignItems: 'center', justifyContent: 'center', padding: 20 },
  formScroll: { width: '100%', maxWidth: 480, maxHeight: '100%' },
  formScrollContent: { flexGrow: 1, justifyContent: 'center', paddingVertical: 12 },
  formCard: { width: '100%', backgroundColor: '#1d1d1f', borderRadius: 24, padding: 24, gap: 12 },
  formHint: { color: '#86868b', fontSize: 12, marginTop: -6, marginBottom: 4 },
  formLabel: { color: '#f5f5f7', fontSize: 12, marginTop: 5 },
  fieldLabel: { color: '#f5f5f7', fontSize: 12, marginTop: 5 },
  formInput: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: '#424245', backgroundColor: '#080808', color: '#f5f5f7', paddingHorizontal: 13, fontSize: 14, outlineStyle: 'none' } as any,
  formActions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 18, marginTop: 10 },
  cancelText: { color: '#cccccc', fontSize: 13 },
  welcomeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 20, marginBottom: 34 },
  welcomeRowCompact: { flexDirection: 'column', alignItems: 'flex-start', gap: 16 },
  welcomeCopy: { flex: 1 },
  eyebrow: { color: '#cccccc', fontSize: 11, letterSpacing: 0.2, marginBottom: 13 },
  greeting: { color: '#f5f5f7', fontSize: 46, lineHeight: 54, fontWeight: '600', letterSpacing: -1.5 },
  greetingCompact: { fontSize: 34, lineHeight: 40 },
  greetingNarrow: { fontSize: 28, lineHeight: 34 },
  sun: { color: '#f5f5f7', fontSize: 27 },
  subtitle: { color: '#86868b', fontSize: 14, marginTop: 7 },
  welcomeActions: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  datePill: { minHeight: 40, paddingHorizontal: 12, borderWidth: 1, borderColor: '#333336', borderRadius: 9, flexDirection: 'row', alignItems: 'center', gap: 8 },
  dateIcon: { color: '#86868b', fontSize: 13 },
  dateText: { color: '#f5f5f7', fontSize: 11 },
  newButton: { minHeight: 42, paddingHorizontal: 16, borderRadius: 9999, backgroundColor: '#0071e3', justifyContent: 'center' },
  newButtonText: { color: '#ffffff', fontSize: 12 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, marginBottom: 42 },
  statCard: { flex: 1, minWidth: 210, minHeight: 164, borderRadius: 28, backgroundColor: '#1d1d1f', padding: 24, justifyContent: 'space-between' },
  statCardCompact: { flexBasis: '45%', minWidth: 120, minHeight: 148, padding: 14 },
  statCardNarrow: { flexBasis: '100%' },
  statTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  statLabel: { color: '#86868b', fontSize: 12 },
  statIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#333336', alignItems: 'center', justifyContent: 'center' },
  statIconGold: { backgroundColor: '#3b3020' },
  statIconRose: { backgroundColor: '#3b2426' },
  statGlyph: { color: '#f5f5f7', fontSize: 16 },
  statValueRow: { flexDirection: 'row', alignItems: 'baseline', gap: 9, marginTop: 12 },
  statValue: { color: '#f5f5f7', fontSize: 34, letterSpacing: -1.1, fontWeight: '600' },
  statValueCompact: { fontSize: 29 },
  statUnit: { color: '#86868b', fontSize: 13 },
  statNote: { color: '#2997ff', fontSize: 11, marginTop: 12 },
  statNoteBlue: { color: '#2997ff' },
  lowerGrid: { flexDirection: 'row', gap: 32 },
  lowerGridCompact: { flexDirection: 'column', gap: 36 },
  lowerPanel: { flex: 1, minWidth: 0 },
  lowerPanelCompact: { flexGrow: 0, flexShrink: 0, flexBasis: 'auto', width: '100%' },
  panelHeader: { minHeight: 54, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 20 },
  panelTitle: { color: '#f5f5f7', fontSize: 19, fontWeight: '600', letterSpacing: 0.13 },
  panelSubtitle: { color: '#86868b', fontSize: 12, marginTop: 5 },
  weekSelect: { borderWidth: 1, borderColor: '#333336', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 },
  weekText: { color: '#f5f5f7', fontSize: 10 },
  receiptSummary: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  receiptValue: { color: '#f5f5f7', fontSize: 30, fontWeight: '600', letterSpacing: -0.8 },
  receiptUnit: { color: '#86868b', fontSize: 14, fontWeight: '400' },
  receiptCaption: { color: '#86868b', fontSize: 11 },
  chartWrap: { marginTop: 22 },
  chartToolbar: { gap: 12, marginBottom: 8 },
  chartPeriodSwitch: { flexDirection: 'row', alignSelf: 'flex-start', padding: 3, gap: 3, borderWidth: 1, borderColor: '#333336', borderRadius: 9999, backgroundColor: '#111111' },
  chartPeriodOption: { minHeight: 30, paddingHorizontal: 12, justifyContent: 'center', borderRadius: 9999 },
  chartPeriodOptionActive: { backgroundColor: '#333336' },
  chartPeriodText: { color: '#86868b', fontSize: 10 },
  chartPeriodTextActive: { color: '#f5f5f7' },
  chartSelection: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: '#333336', borderRadius: 10, backgroundColor: '#141414' },
  chartSelectedLabel: { color: '#86868b', fontSize: 11 },
  chartSelectedValue: { color: '#f5f5f7', fontSize: 12, fontWeight: '600' },
  chartTotalRow: { flexDirection: 'row', alignItems: 'baseline', gap: 10, marginBottom: 6 },
  chartTotal: { color: '#f5f5f7', fontSize: 30, letterSpacing: -0.7, fontWeight: '600' },
  chartTotalUnit: { color: '#86868b', fontSize: 13, fontWeight: '400' },
  chartGrowth: { color: '#2997ff', fontSize: 11 },
  chartGrowthMuted: { color: '#86868b' },
  chartLegend: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 8 },
  legendDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#2997ff' },
  legendText: { color: '#86868b', fontSize: 11 },
  panelArrow: { color: '#cccccc', fontSize: 17 },
  shipmentRow: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 12, borderTopWidth: 1, borderTopColor: 'rgba(134,134,139,0.3)' },
  shipmentIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#1d1d1f', justifyContent: 'center', alignItems: 'center' },
  shipmentCopy: { flex: 1, gap: 4 },
  shipmentName: { color: '#f5f5f7', fontSize: 12 },
  shipmentDetail: { color: '#86868b', fontSize: 10 },
  progressTrack: { height: 3, borderRadius: 2, overflow: 'hidden', backgroundColor: '#333336', marginTop: 4 },
  progressFill: { height: '100%', backgroundColor: '#0071e3', borderRadius: 2 },
  progressText: { color: '#86868b', fontSize: 10 },
});
