import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#000000' },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1 },
  page: { flex: 1, minHeight: '100%', paddingHorizontal: 64 },
  topBar: {
    minHeight: 64,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(134,134,139,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  logo: { width: 142, height: 38 },
  main: {
    flex: 1,
    width: '100%',
    maxWidth: 1170,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 48,
    paddingVertical: 24,
  },
  intro: { flex: 1, maxWidth: 540, paddingVertical: 8 },
  eyebrowRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  eyebrowLine: { width: 22, height: 1, backgroundColor: '#86868b' },
  eyebrow: { color: '#cccccc', fontSize: 12, letterSpacing: -0.12, fontWeight: '400' },
  headline: {
    color: '#f5f5f7',
    fontSize: 48,
    lineHeight: 51,
    letterSpacing: -1.8,
    fontWeight: '600',
  },
  description: {
    color: '#86868b',
    fontSize: 17,
    lineHeight: 25,
    letterSpacing: -0.374,
    maxWidth: 395,
    marginTop: 12,
  },
  produceFrame: {
    width: '100%',
    maxWidth: 430,
    aspectRatio: 1.65,
    maxHeight: 210,
    marginTop: 12,
    overflow: 'hidden',
    borderRadius: 28,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  produceImage: { width: '100%', height: '100%' },
  imageCaption: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(29,29,31,0.88)',
    borderRadius: 9999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  captionDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#cccccc' },
  captionText: { color: '#f5f5f7', fontSize: 10, letterSpacing: -0.1 },
  featureList: { marginTop: 10, maxWidth: 440 },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(134,134,139,0.3)',
    gap: 12,
  },
  featureItemLast: { borderBottomWidth: 0 },
  featureNumber: { color: '#86868b', fontSize: 12, letterSpacing: -0.12, width: 24 },
  featureCopy: { flex: 1, gap: 3 },
  featureTitle: { color: '#f5f5f7', fontSize: 14, fontWeight: '400' },
  featureDetail: { color: '#86868b', fontSize: 12 },
  featureArrow: { color: '#cccccc', fontSize: 16 },
  loginCard: {
    width: 420,
    maxWidth: '100%',
    backgroundColor: '#1d1d1f',
    borderWidth: 1,
    borderColor: 'rgba(134,134,139,0.3)',
    borderRadius: 28,
    padding: 26,
  },
  cardHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  cardEyebrow: { color: '#86868b', fontSize: 12, letterSpacing: -0.12, marginBottom: 6 },
  cardTitle: { color: '#f5f5f7', fontSize: 28, lineHeight: 32, letterSpacing: 0.196, fontWeight: '600' },
  cardMark: { width: 36, height: 36, opacity: 0.9 },
  fieldLabel: { color: '#f5f5f7', fontSize: 12, fontWeight: '400', marginBottom: 10 },
  input: {
    height: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(134,134,139,0.5)',
    backgroundColor: '#000000',
    paddingHorizontal: 15,
    color: '#f5f5f7',
    fontSize: 17,
    letterSpacing: -0.374,
    marginBottom: 14,
  },
  passwordLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  linkText: { color: '#2997ff', fontSize: 12, marginBottom: 10 },
  passwordWrap: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(134,134,139,0.5)',
    backgroundColor: '#000000',
    marginBottom: 16,
  },
  passwordInput: { flex: 1, minWidth: 0, height: '100%', paddingHorizontal: 15, color: '#f5f5f7', fontSize: 17, letterSpacing: -0.374 },
  visibilityButton: { paddingHorizontal: 10, paddingVertical: 12 },
  visibilityText: { color: '#cccccc', fontSize: 12 },
  submitButton: {
    minHeight: 46,
    backgroundColor: '#0071e3',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
  },
  submitPressed: { opacity: 0.82 },
  submitText: { color: '#ffffff', fontWeight: '400', fontSize: 17, letterSpacing: -0.374 },
  arrow: { fontSize: 17 },
  separatorRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 13 },
  separatorLine: { height: StyleSheet.hairlineWidth, flex: 1, backgroundColor: 'rgba(134,134,139,0.3)' },
  separatorText: { color: '#86868b', fontSize: 12 },
  googleButton: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(134,134,139,0.5)',
    borderRadius: 9999,
    backgroundColor: '#000000',
  },
  googlePressed: { opacity: 0.78 },
  googleMark: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center' },
  googleG: { color: '#4285F4', fontSize: 14, fontWeight: '600' },
  googleText: { color: '#f5f5f7', fontSize: 14 },
  message: { color: '#f5f5f7', fontSize: 12, lineHeight: 18, marginTop: 14, textAlign: 'center' },
  demoAccounts: { borderTopWidth: 1, borderTopColor: '#333336', marginTop: 20, paddingTop: 16, gap: 8 },
  demoTitle: { color: '#86868b', fontSize: 10, letterSpacing: 0.8, marginBottom: 2 },
  demoAccount: { minHeight: 38, borderRadius: 10, backgroundColor: '#2a2a2d', paddingHorizontal: 12, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 4 },
  demoRole: { color: '#f5f5f7', fontSize: 11, fontWeight: '600' },
  demoEmail: { color: '#cccccc', fontSize: 11 },
  demoHint: { color: '#86868b', fontSize: 11, lineHeight: 16, marginTop: 2 },
  secureNote: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginTop: 14 },
  lockIcon: { color: '#cccccc', fontSize: 14 },
  secureText: { color: '#86868b', fontSize: 12 },
  footer: {
    minHeight: 48,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(134,134,139,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerText: { color: '#86868b', fontSize: 12, letterSpacing: -0.12 },
  footerCenter: { color: '#cccccc', fontSize: 12, letterSpacing: -0.12 },
  pageCompact: { paddingHorizontal: 22 },
  pageNarrow: { paddingHorizontal: 16 },
  topBarShort: { minHeight: 48 },
  mainShort: { paddingVertical: 10, gap: 36 },
  produceFrameShort: { maxHeight: 160, marginTop: 8 },
  featureListShort: { marginTop: 6 },
  loginCardShort: { padding: 20 },
  mainCompact: { flexDirection: 'column', alignItems: 'stretch', gap: 24, paddingVertical: 34 },
  mainTablet: { gap: 36 },
  introCompact: { maxWidth: 520, paddingVertical: 0 },
  headlineTablet: { fontSize: 46, lineHeight: 51 },
  headlineCompact: { fontSize: 42, lineHeight: 46, letterSpacing: -1.7 },
  headlineNarrow: { fontSize: 36, lineHeight: 40 },
  loginCardTablet: { width: 390, padding: 27 },
  loginCardCompact: { width: '100%', maxWidth: 480, alignSelf: 'center', padding: 25, borderRadius: 24 },
  loginCardNarrow: { padding: 20 },
  footerCompact: { minHeight: 54 },
});
